<?php
require __DIR__.'/integration.php';
$baseline = count($passed);
wp_set_current_user($admin->ID);
success(request('PUT','admin/plans/free',array('max_active_assistants'=>1)));
$id=wp_create_user('downgrade-'.wp_generate_password(10,false,false),'Local-test-only!123');
(new WP_User($id))->set_role('coachpro_user');
update_user_meta($id,'coachpro_free_credits_next',time()+30*DAY_IN_SECONDS);
success(request('PUT','admin/users/'.$id,array('plan'=>'pro','credits'=>20)));
wp_set_current_user($id);
$project=success(request('POST','projects',array('name'=>'Retained project')));
$custom=success(request('POST','assistants',array('name'=>'Retained custom assistant','system_prompt'=>'Test only')));
$assistants=CoachPro_DB::get_rows('assistants',array('is_prebuilt'=>1),'created_at ASC',2);
$convs=array();
foreach($assistants as $i=>$a) {
    success(request('POST','assistants/'.$a['id'].'/activate'));
    // Ensure a deterministic first activation, independent of second-resolution ties.
    $wpdb->update(CoachPro_DB::table('user_active_assistants'),array('activated_at'=>'2026-01-0'.($i+1).' 00:00:00'),array('user_id'=>$id,'assistant_id'=>$a['id']));
    $convs[]=success(request('POST','conversations',array('project_id'=>$project['id'],'assistant_id'=>$a['id'])));
}
$rid=wp_generate_uuid4();
$payload=array('conversation_id'=>$convs[1]['id'],'message'=>'Quick Chat retry','request_id'=>$rid);
$first=success(request('POST','chat',$payload));
$http_before=count($captured);
$retry=success(request('POST','chat',$payload));
check($retry['message_id']===$first['message_id'] && $retry['balance']===19 && count($captured)===$http_before && CoachPro_DB::count('messages',array('conversation_id'=>$convs[1]['id']))===2, 'Quick Chat retry returns the committed answer with no duplicate charge or messages');
$http_mode='fail';$failed_id=wp_generate_uuid4();$payload['request_id']=$failed_id;
check(request('POST','chat',$payload)->get_status()>=400 && CoachPro_Credits::get_balance($id)===19, 'Failed Quick Chat attempt is refunded');
$http_mode='success';$failed=request('POST','chat',$payload);
check($failed->get_status()===409 && $failed->get_data()['code']==='request_failed', 'A refunded terminal failure is distinguished from an uncertain pending request');
$pending_id=wp_generate_uuid4();
$wpdb->insert(CoachPro_DB::table('chat_requests'),array('id'=>$pending_id,'user_id'=>$id,'conversation_id'=>$convs[1]['id'],'message_id'=>wp_generate_uuid4(),'credits'=>0,'status'=>'pending'));
$payload['request_id']=$pending_id;$pending=request('POST','chat',$payload);
check($pending->get_status()===409 && $pending->get_data()['code']==='request_processed', 'Pending retries cannot be mistaken for refunded failures');
CoachPro_Chat_API::refund($pending_id);
$payload['request_id']=wp_generate_uuid4();success(request('POST','chat',$payload));
check(CoachPro_Credits::get_balance($id)===18, 'A new ID after a confirmed failure charges exactly once');
$saved=success(request('POST','saved-responses',array('message_id'=>$first['message_id'])));
$activation_before=CoachPro_DB::get_rows('user_active_assistants',array('user_id'=>$id),'id ASC');
$messages_before=CoachPro_DB::count('messages',array('conversation_id'=>$convs[1]['id']));
update_user_meta($id,'coachpro_plan_renews','2000-01-01 00:00:00');
// No explicit refresh: direct chat must enforce expiry on its own.
$http_before=count($captured);
$blocked=request('POST','chat',array('conversation_id'=>$convs[1]['id'],'message'=>'Blocked after expiry'));
check($blocked->get_status()===403 && CoachPro_Credits::get_balance($id)===18 && count($captured)===$http_before, 'Direct chat with an excess assistant is blocked after Pro expiry without billing');
$rows=success(request('GET','assistants'));
$by_id=array_column($rows,null,'id');
check((int)$by_id[$assistants[0]['id']]['is_activated']===1 && (int)$by_id[$assistants[1]['id']]['is_activated']===0 && (int)$by_id[$assistants[1]['id']]['is_activation_suspended']===1, 'Assistant listing exposes one effective activation and marks the excess as paused');
check(CoachPro_DB::get_rows('user_active_assistants',array('user_id'=>$id),'id ASC')===$activation_before, 'Downgrade preserves every stored activation');
check(CoachPro_DB::get_row('projects',$project['id']) && CoachPro_DB::get_row('assistants',$custom['id']) && CoachPro_DB::get_row('saved_responses',$saved['id']) && CoachPro_DB::count('messages',array('conversation_id'=>$convs[1]['id']))===$messages_before, 'Downgrade preserves projects, custom assistants, saved responses, and messages');
check(count(success(request('GET','conversations/'.$convs[1]['id'].'/messages')))===$messages_before, 'Paused assistant conversation history remains readable');
check(request('POST','conversations',array('project_id'=>$project['id'],'assistant_id'=>$assistants[1]['id']))->get_status()===403, 'Paused assistant cannot create a new conversation');
check(request('POST','assistants/'.$assistants[1]['id'].'/activate')->get_status()===403, 'Repeated activation cannot bypass the downgraded plan limit');
check(CoachPro_Assistants_API::user_can_use(CoachPro_DB::get_row('assistants',$custom['id']),$id), 'Custom assistant access is unchanged');
$reply=success(request('POST','chat',array('conversation_id'=>$convs[0]['id'],'message'=>'Allowed after expiry')));
check($reply['balance']===17, 'Earliest activated assistant remains usable and charges its configured cost');
wp_set_current_user($admin->ID);success(request('PUT','admin/users/'.$id,array('plan'=>'pro')));wp_set_current_user($id);
check(count(CoachPro_Credits::active_prebuilt_ids($id))===2, 'Upgrade restores both preserved activations');
success(request('POST','chat',array('conversation_id'=>$convs[1]['id'],'message'=>'Restored after upgrade')));
check(CoachPro_Credits::get_balance($id)===16, 'Previously paused conversation resumes after upgrade');
wp_set_current_user($admin->ID);success(request('PUT','admin/users/'.$id,array('plan'=>'free')));wp_set_current_user($id);
check(count(CoachPro_Credits::active_prebuilt_ids($id))===1 && request('POST','chat',array('conversation_id'=>$convs[1]['id'],'message'=>'Direct downgrade'))->get_status()===403 && CoachPro_Credits::get_balance($id)===16, 'Explicit admin downgrade also limits access without charging blocked chat');
success(request('DELETE','assistants/'.$assistants[0]['id'].'/activate'));
check(CoachPro_Credits::active_prebuilt_ids($id)===array($assistants[1]['id']), 'Deactivating the allowed assistant promotes the next preserved activation');
wp_set_current_user($admin->ID);success(request('PUT','admin/plans/free',array('max_active_assistants'=>0)));wp_set_current_user($id);
check(CoachPro_Credits::active_prebuilt_ids($id)===array() && !CoachPro_Assistants_API::user_can_use($assistants[1],$id), 'Configured zero-active-assistant quota blocks all prebuilt access');
wp_set_current_user($admin->ID);success(request('PUT','admin/plans/free',array('max_active_assistants'=>1)));
echo (count($passed)-$baseline)." credit regression checks passed.\n";
foreach(array_slice($passed,$baseline) as $line) echo "PASS $line\n";
