<?php
require __DIR__ . '/bootstrap.php';
$passed = array();
function check($condition, $message) {
    global $passed;
    if (!$condition) throw new RuntimeException('FAIL: '.$message);
    $passed[] = $message;
}
function request($method, $path, $data = array()) {
    $request = new WP_REST_Request($method, '/coachpro/v1/'.$path);
    $request->set_header('X-WP-Nonce', wp_create_nonce('wp_rest'));
    if ('GET' === $method) $request->set_query_params($data);
    else { $request->set_header('Content-Type', 'application/json'); $request->set_body(wp_json_encode($data)); }
    return rest_do_request($request);
}
function success($response) {
    if ($response->get_status() >= 400) throw new RuntimeException(wp_json_encode($response->get_data()));
    return $response->get_data();
}
// Destructive setup is restricted to this disposable test schema and plugin prefix.
if (DB_NAME !== 'coachpro_integration_test' || DB_HOST !== '127.0.0.1:3308') throw new RuntimeException('Unsafe test database.');
foreach ($wpdb->get_col("SHOW TABLES LIKE 'cpt_coachpro_%'") as $table) $wpdb->query("DROP TABLE `$table`");
foreach ($wpdb->get_col("SELECT option_name FROM {$wpdb->options} WHERE option_name LIKE 'coachpro_%'") as $name) delete_option($name);
CoachPro_Activator::activate();
check(count($wpdb->get_col("SHOW TABLES LIKE 'cpt_coachpro_%'")) === 13, 'Activation creates all 13 tables');
$wpdb->update(CoachPro_DB::table('plans'), array('price_pkr'=>1234), array('id'=>'basic'));
$assistant_count = CoachPro_DB::count('assistants');
$pack_count = CoachPro_DB::count('credit_packs');
CoachPro_Activator::activate();
check(CoachPro_DB::count('assistants') === $assistant_count && CoachPro_DB::count('credit_packs') === $pack_count, 'Reactivation does not duplicate defaults');
check((int)CoachPro_DB::get_row('plans','basic')['price_pkr'] === 1234, 'Reactivation preserves edited plans');
$admin = get_user_by('login','testadmin');
wp_set_current_user($admin->ID);
update_option('coachpro_openai_key','test-key');
update_option('coachpro_anthropic_key','other-key');
success(request('POST','admin/provider-settings',array('providers'=>array('openai'=>array('api_key'=>'new-key'),'anthropic'=>array('api_key'=>'')))));
check(get_option('coachpro_anthropic_key') === 'other-key', 'Blank provider fields preserve keys');
success(request('POST','admin/provider-settings',array('providers'=>array('anthropic'=>array('clear_key'=>true)))));
check(!get_option('coachpro_anthropic_key'), 'Explicit removal clears only the selected key');
success(request('PUT','admin/plans/free',array('max_projects'=>7,'max_saved_responses'=>null,'max_active_assistants'=>2)));
check((int)CoachPro_DB::get_row('plans','free')['max_projects'] === 7 && null === CoachPro_DB::get_row('plans','free')['max_saved_responses'], 'Plan updates save numeric and unlimited quotas');
$user_id = wp_create_user('fixture-'.wp_generate_password(8,false,false), 'Test-password!123', wp_generate_password(8,false,false).'@example.test');
check(!is_wp_error($user_id), 'Test user created');
wp_set_current_user($user_id);
CoachPro_Credits::refresh_plan($user_id);
$balance = CoachPro_Credits::get_balance($user_id);
CoachPro_Credits::refresh_plan($user_id);
check(CoachPro_Credits::get_balance($user_id) === $balance, 'Free allowance is granted once per cycle');
CoachPro_Credits::set($user_id, 10);
CoachPro_Credits::get_balance($user_id); // Prime metadata cache.
check(CoachPro_Credits::add($user_id,0,'admin_adjust') === 10, 'Adding zero preserves balance');
check(CoachPro_Credits::deduct($user_id,3,wp_generate_uuid4(),'gpt-4o-mini') === 7, 'Deduction returns fresh balance after priming cache');
$tx = CoachPro_DB::get_rows('transactions',array('user_id'=>$user_id),'created_at DESC',1);
check((int)$tx[0]['balance_after'] === 7, 'Ledger balance matches updated balance');
check(is_wp_error(CoachPro_Credits::deduct($user_id,20,wp_generate_uuid4(),'gpt-4o-mini')), 'Insufficient balance rejects deduction');
$before = CoachPro_Credits::get_balance($user_id);
$rollback = CoachPro_DB::transaction(function() use($user_id) { CoachPro_Credits::add($user_id,99,'admin_adjust'); return new WP_Error('injected','Injected failure'); },$user_id);
check(is_wp_error($rollback) && CoachPro_Credits::get_balance($user_id) === $before, 'Failed transaction rolls back balance and invalidates cache');
$profile = success(request('PUT','profile',array('display_name'=>'Changed name')));
check($profile['name'] === 'Changed name', 'Display name changes do not require password');
check(request('PUT','profile',array('email'=>'new@example.test'))->get_status() === 403, 'Email changes require current password');
$profile = success(request('PUT','profile',array('email'=>wp_generate_password(8,false,false).'@example.test','current_password'=>'Test-password!123')));
check(strpos($profile['email'],'@example.test') !== false, 'Verified email changes succeed');
$project = success(request('POST','projects',array('name'=>'Project')));
$assistant = CoachPro_DB::get_rows('assistants',array('is_prebuilt'=>1),'created_at ASC',1)[0];
success(request('POST','assistants/'.$assistant['id'].'/activate'));
success(request('POST','assistants/'.$assistant['id'].'/activate'));
check(CoachPro_DB::count('user_active_assistants',array('user_id'=>$user_id,'assistant_id'=>$assistant['id'])) === 1, 'Repeated activation is idempotent');
$conversation = success(request('POST','conversations',array('project_id'=>$project['id'],'assistant_id'=>$assistant['id'])));
$captured = array();
$http_mode = 'success';
add_filter('pre_http_request',function($pre,$args,$url) use (&$captured,&$http_mode) {
    if (strpos($url,'api.openai.com') === false && strpos($url,'api.anthropic.com') === false && strpos($url,'generativelanguage.googleapis.com') === false) return $pre;
    $captured[] = json_decode($args['body'] ?? '{}',true);
    if ($http_mode === 'fail') return new WP_Error('provider_down','Provider unavailable',array('status'=>502));
    if ($http_mode === 'empty') return array('response'=>array('code'=>200),'body'=>'{}','headers'=>array());
    return array('response'=>array('code'=>200),'body'=>wp_json_encode(array('choices'=>array(array('message'=>array('content'=>'Test answer'))),'content'=>array(array('text'=>'Test answer')),'candidates'=>array(array('content'=>array('parts'=>array(array('text'=>'Test answer'))))))),'headers'=>array());
},10,3);
CoachPro_Credits::set($user_id,10);
$request_id = wp_generate_uuid4();
$chat_data = array('conversation_id'=>$conversation['id'],'message'=>'Hello','request_id'=>$request_id);
$chat = success(request('POST','chat',$chat_data));
check($chat['balance'] === 9 && CoachPro_DB::count('messages',array('conversation_id'=>$conversation['id'])) === 2, 'Chat charges once and saves one user/assistant pair');
$again = success(request('POST','chat',$chat_data));
check($again['message_id'] === $chat['message_id'] && CoachPro_Credits::get_balance($user_id) === 9, 'Retrying a completed request does not charge again');
$http_mode = 'fail';
$failed = request('POST','chat',array('conversation_id'=>$conversation['id'],'message'=>'Fail'));
check($failed->get_status() >= 400 && CoachPro_Credits::get_balance($user_id) === 9, 'Provider failure refunds reserved credits');
check(CoachPro_DB::count('messages',array('conversation_id'=>$conversation['id'])) === 2, 'Failed chat leaves no partial messages');
$http_mode = 'empty';
check(request('POST','chat',array('conversation_id'=>$conversation['id'],'message'=>'Empty'))->get_status() === 502 && CoachPro_Credits::get_balance($user_id) === 9, 'Empty responses are rejected and refunded');
$http_mode = 'success';
$recovery_id = wp_generate_uuid4();
$recovery_message = wp_generate_uuid4();
CoachPro_Credits::deduct($user_id, 2, $recovery_message, 'gpt-4o-mini');
$wpdb->insert(CoachPro_DB::table('chat_requests'), array('id'=>$recovery_id, 'user_id'=>$user_id, 'conversation_id'=>$conversation['id'], 'message_id'=>$recovery_message, 'credits'=>2, 'status'=>'pending', 'created_at'=>gmdate('Y-m-d H:i:s', time()-11*MINUTE_IN_SECONDS)));
check(request('DELETE','conversations/'.$conversation['id'])->get_status() === 409, 'Pending chat prevents conversation deletion');
check(request('DELETE','projects/'.$project['id'])->get_status() === 409, 'Pending chat prevents project deletion');
CoachPro_Chat_API::recover_pending();
check(CoachPro_Credits::get_balance($user_id) === 9 && CoachPro_DB::get_row('chat_requests',$recovery_id)['status'] === 'failed', 'Interrupted chat recovery refunds stale reservations');
CoachPro_Chat_API::recover_pending();
CoachPro_Chat_API::refund($recovery_id);
check(CoachPro_Credits::get_balance($user_id) === 9 && CoachPro_DB::count('transactions',array('reference_id'=>$recovery_message,'kind'=>'refund')) === 1, 'Repeated recovery refunds an interrupted chat exactly once');
check(request('POST','chat',array('conversation_id'=>$conversation['id'],'message'=>'Premium','model_id'=>'gpt-4o'))->get_status() === 403, 'Model plan restrictions are enforced');
$payment = success(request('POST','payments',array('kind'=>'subscription','plan_id'=>'basic','method'=>'jazzcash','amount_pkr'=>1,'sender_name'=>'Test','reference_no'=>wp_generate_uuid4())));
check((int)$payment['amount_pkr'] === 1234, 'Payment prices come from the server');
check(request('POST','payments',array('kind'=>'subscription','method'=>'jazzcash','amount_pkr'=>999))->get_status() === 400, 'Payments without a product are rejected');
wp_set_current_user($admin->ID);
$before = CoachPro_Credits::get_balance($user_id);
success(request('POST','admin/payments/'.$payment['id'].'/approve'));
check(CoachPro_Credits::get_balance($user_id) === $before + 500, 'Approval grants purchased credits');
check(request('POST','admin/payments/'.$payment['id'].'/approve')->get_status() === 409, 'Repeated approval is rejected');
check(request('POST','admin/payments/'.$payment['id'].'/reject')->get_status() === 409, 'Approved payments cannot be rejected and reapproved');
check(request('DELETE','admin/assistants/'.$assistant['id'])->get_status() === 409, 'Deleting an assistant with conversations is blocked');
check(request('DELETE','admin/plans/basic')->get_status() === 409, 'Deleting a referenced plan is blocked');
wp_set_current_user($user_id);
$expiry = get_user_meta($user_id,'coachpro_plan_renews',true);
$payment2 = success(request('POST','payments',array('kind'=>'subscription','plan_id'=>'basic','method'=>'jazzcash','sender_name'=>'Test','reference_no'=>wp_generate_uuid4())));
wp_set_current_user($admin->ID);
success(request('POST','admin/payments/'.$payment2['id'].'/approve'));
check(strtotime(get_user_meta($user_id,'coachpro_plan_renews',true).' UTC') === strtotime($expiry.' UTC') + 30*DAY_IN_SECONDS, 'Early renewal preserves remaining subscription time');
update_user_meta($user_id,'coachpro_plan_renews','2000-01-01 00:00:00');
CoachPro_Credits::refresh_plan($user_id);
check(get_user_meta($user_id,'coachpro_plan',true) === 'free', 'Expired paid plans fall back to free');
wp_set_current_user($user_id);
for($i=0;$i<205;$i++) $wpdb->insert(CoachPro_DB::table('messages'),array('id'=>wp_generate_uuid4(),'conversation_id'=>$conversation['id'],'user_id'=>$user_id,'role'=>'user','content'=>'History '.$i,'created_at'=>gmdate('Y-m-d H:i:s',time()+$i+1)));
$recent = success(request('GET','conversations/'.$conversation['id'].'/messages',array('per_page'=>100,'page'=>1)));
$older = success(request('GET','conversations/'.$conversation['id'].'/messages',array('per_page'=>100,'page'=>2)));
check(count($recent)===100 && end($recent)['content']==='History 204' && count($older)===100, 'Message pagination returns latest messages and older pages');
CoachPro_AI_Provider::schedule_summary($conversation['id']);
check((bool)wp_next_scheduled('coachpro_summarize',array($conversation['id'])), 'Summary scheduling catches a crossed threshold');
CoachPro_AI_Provider::run_summary_cron($conversation['id']);
$sum = CoachPro_DB::get_rows('conv_summaries',array('conversation_id'=>$conversation['id']),'updated_at DESC')[0];
check((int)$sum['message_count_at_summary']===40, 'Summary processes first incremental batch');
CoachPro_AI_Provider::run_summary_cron($conversation['id']);
$sum = CoachPro_DB::get_rows('conv_summaries',array('conversation_id'=>$conversation['id']),'updated_at DESC')[0];
check((int)$sum['message_count_at_summary']===80 && strpos(end($captured)['messages'][0]['content'],'Previous summary:')!==false, 'Summary advances and carries previous memory');
CoachPro_AI_Provider::call_anthropic('https://api.anthropic.com','test','test',array(array('role'=>'system','content'=>'Memory'),array('role'=>'system','content'=>'Persona'),array('role'=>'user','content'=>'Hi')));
check(end($captured)['system']==="Memory\n\nPersona", 'Anthropic retains summary and persona');
CoachPro_AI_Provider::call_gemini('https://generativelanguage.googleapis.com/v1beta','test','test',array(array('role'=>'system','content'=>'Memory'),array('role'=>'system','content'=>'Persona'),array('role'=>'user','content'=>'Hi')));
check(end($captured)['systemInstruction']['parts'][0]['text']==="Memory\n\nPersona", 'Gemini retains summary and persona');
success(request('DELETE','projects/'.$project['id']));
check(CoachPro_DB::count('messages',array('conversation_id'=>$conversation['id']))===0 && CoachPro_DB::count('conv_summaries',array('conversation_id'=>$conversation['id']))===0, 'Project deletion cascades through messages and summaries');
echo count($passed)." integration checks passed.\n";
foreach($passed as $line) echo "PASS $line\n";
